### ISSUE TITLE
Correct package for package.yaml deprecation.

### ISSUE THREAD

**Issue by capn-freako** [conal/linalg#1]
Currently, importing this package into a larger Haskell `stack` project, via:

```yaml
extra-deps:
- git: https://github.com/conal/linalg.git
  commit: 038cb7e28f8e361f4a181d8f9158410b031fbd79
```

in the `stack.yaml` file, yields this warning in response to a `stack build` command:

```
$ stack build
Cloning 038cb7e28f8e361f4a181d8f9158410b031fbd79 from https://github.com/conal/linalg.git
DEPRECATED: The package at Repo from https://github.com/conal/linalg.git, commit 038cb7e28f8e361f4a1
81d8f9158410b031fbd79 does not include a cabal file.                                               
Instead, it includes an hpack package.yaml file for generating a cabal file.
This usage is deprecated; please see https://github.com/commercialhaskell/stack/issues/5210.
Support for this workflow will be removed in the future.
```

- [ ] Add a cabal file, and remove the `package.yaml` file, in response to this deprecation.
